# Generated by Django 5.2.4 on 2025-07-29 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_two_factor_enabled_twofactorcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorcode',
            name='purpose',
            field=models.CharField(choices=[('enable_2fa', 'Enable 2FA'), ('disable_2fa', 'Disable 2FA'), ('login', 'Login Verification'), ('set_password', 'Set Password'), ('reset_password', 'Reset Password')], default='enable_2fa', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailRequestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('request_type', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('two_factor_code', 'Two Factor Code')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'request_type', 'created_at'], name='authenticat_email_35440c_idx'), models.Index(fields=['user', 'request_type', 'created_at'], name='authenticat_user_id_ffdf2c_idx')],
            },
        ),
    ]
