# Generated by Django 5.2.5 on 2025-09-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_model_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatanalytics',
            name='date',
            field=models.DateField(),
        ),
    ]
